name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 888762633130.dkr.ecr.us-east-2.amazonaws.com

      - name: Build and push Docker image
        run: |
          IMAGE_URI=888762633130.dkr.ecr.us-east-2.amazonaws.com/devops-notes-app:latest
          docker build -t $IMAGE_URI ./devops-notes-app
          docker push $IMAGE_URI

      - name: Update K8s deployment
        run: |
          aws eks update-kubeconfig --name devops-notes-cluster --region us-east-2
          kubectl set image deployment/notes-deployment notes=888762633130.dkr.ecr.us-east-2.amazonaws.com/devops-notes-app:latest
          kubectl rollout status deployment/notes-deployment
